[workspace]
resolver = "3"
members = [
    "crates/cargo-agentforge",
    "crates/agentforge-domain",
    "crates/agentforge-core",
    "crates/agentforge-builder",
]

[workspace.package]
edition = "2024"
rust-version = "1.95.0"
authors = ["Suradet Pratomsak"]
license = "MIT"

[workspace.dependencies]
thiserror = "2"
serde = { version = "1", features = ["derive"] }
