use std::path::PathBuf;

use agentforge_domain::manifest::RuleManifest;

use crate::exit::ExitCode;
use crate::fs::InstallTarget;

#[derive(Debug, Clone)]
pub struct Config {
  pub manifest: RuleManifest,
  pub agents_md_path: PathBuf,
  pub manifest_path: PathBuf,
  pub force: bool,
  pub dry_run: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Outcome {
  Installed,
  Upgraded,
  Skipped,
  Conflict { edited_rules: Vec<String> },
  DryRun { would_install: bool },
}

impl Outcome {
  pub fn exit_code(&self) -> ExitCode {
    match self {
      Self::Installed => ExitCode::Installed,
      Self::Upgraded => ExitCode::Upgraded,
      Self::Skipped => ExitCode::Skipped,
      Self::Conflict { .. } => ExitCode::Conflict,
      Self::DryRun { .. } => ExitCode::DryRun,
    }
  }
}

#[derive(Debug, thiserror::Error)]
pub enum CoreError {
  #[error("failed to read manifest at {path}: {source}")]
  ManifestRead {
    path: PathBuf,
    source: Box<dyn std::error::Error + Send + Sync>,
  },

  #[error("failed to deserialize existing manifest: {0}")]
  ManifestDeserialize(String),

  #[error("failed to write {path}: {reason}")]
  WriteFailed { path: PathBuf, reason: String },

  #[error("manifest version mismatch: installed={installed}, incoming={incoming}")]
  VersionMismatch { installed: String, incoming: String },
}

pub fn install<F: InstallTarget>(fs: &F, config: &Config) -> Result<Outcome, CoreError> {
  let existing = fs.read_file(&config.manifest_path);

  match existing {
    None => {
      if config.dry_run {
        return Ok(Outcome::DryRun {
          would_install: true,
        });
      }
      write_files(fs, config)?;
      Ok(Outcome::Installed)
    }
    Some(json) => {
      let existing_manifest: RuleManifest =
        serde_json::from_str(&json).map_err(|e| CoreError::ManifestDeserialize(e.to_string()))?;

      if existing_manifest.ruleset_version != config.manifest.ruleset_version {
        return Err(CoreError::VersionMismatch {
          installed: existing_manifest.ruleset_version,
          incoming: config.manifest.ruleset_version.clone(),
        });
      }

      let edited_rules = find_edited_rules(&existing_manifest, &config.manifest);

      if !edited_rules.is_empty() && !config.force {
        return Ok(Outcome::Conflict { edited_rules });
      }

      if existing_manifest == config.manifest {
        return Ok(Outcome::Skipped);
      }

      if config.dry_run {
        return Ok(Outcome::DryRun {
          would_install: true,
        });
      }

      write_files(fs, config)?;
      Ok(Outcome::Upgraded)
    }
  }
}

fn find_edited_rules(existing: &RuleManifest, incoming: &RuleManifest) -> Vec<String> {
  let mut edited = Vec::new();

  for incoming_rule in &incoming.rules {
    if let Some(existing_rule) = existing.rules.iter().find(|r| r.id == incoming_rule.id)
      && existing_rule.body_checksum != incoming_rule.body_checksum
    {
      edited.push(incoming_rule.id.clone());
    }
  }

  edited
}

fn write_files<F: InstallTarget>(fs: &F, config: &Config) -> Result<(), CoreError> {
  let manifest_json =
    serde_json::to_string_pretty(&config.manifest).map_err(|e| CoreError::WriteFailed {
      path: config.manifest_path.clone(),
      reason: e.to_string(),
    })?;

  fs.write_file(&config.manifest_path, &manifest_json)
    .map_err(|reason| CoreError::WriteFailed {
      path: config.manifest_path.clone(),
      reason,
    })?;

  let agents_md = generate_agents_md(&config.manifest);
  fs.write_file(&config.agents_md_path, &agents_md)
    .map_err(|reason| CoreError::WriteFailed {
      path: config.agents_md_path.clone(),
      reason,
    })?;

  Ok(())
}

fn generate_agents_md(manifest: &RuleManifest) -> String {
  let mut out = format!(
    "# AGENTS-RUST.md\n\n\
         > Auto-generated by `cargo agentforge install`. Do not edit by hand.\n\n\
         Ruleset version: `{}`\n\n",
    manifest.ruleset_version
  );

  for rule in &manifest.rules {
    let severity = rule.severity.to_uppercase();
    out.push_str(&format!(
      "## [{}] {} ({})\n\n",
      rule.id, rule.title, severity
    ));
    out.push_str(&format!("<!-- checksum: {} -->\n\n", rule.body_checksum));
  }

  for ovr in &manifest.overrides {
    out.push_str(&format!(
      "<!-- override: {} → {} -->\n",
      ovr.target_rule_id, ovr.reason
    ));
  }

  out
}

#[cfg(test)]
mod tests {
  use super::*;
  use crate::fs::MockFs;
  use agentforge_domain::manifest::RuleManifest;
  use agentforge_domain::rule::{Rule, RuleSet, Severity};
  use agentforge_domain::rule_id::RuleId;

  fn make_manifest(version: &str) -> RuleManifest {
    let mut rs = RuleSet::new(version.into());
    rs.add_rule(Rule::new(
      RuleId::new("0").unwrap(),
      "0".into(),
      "Golden Rules".into(),
      "These rules always apply.".into(),
      Severity::Mandatory,
    ))
    .unwrap();
    rs.add_rule(Rule::new(
      RuleId::new("5.2").unwrap(),
      "5".into(),
      "Error Handling".into(),
      "Use thiserror.".into(),
      Severity::Recommended,
    ))
    .unwrap();
    RuleManifest::from_rule_set(&rs, "2026-01-01T00:00:00Z").unwrap()
  }

  fn make_config(manifest: RuleManifest) -> Config {
    Config {
      manifest,
      agents_md_path: "/project/AGENTS-RUST.md".into(),
      manifest_path: "/project/.agentforge.json".into(),
      force: false,
      dry_run: false,
    }
  }

  #[test]
  fn install_fresh() {
    let fs = MockFs::new();
    let config = make_config(make_manifest("0.1.0"));
    let outcome = install(&fs, &config).unwrap();
    assert_eq!(outcome, Outcome::Installed);
    assert_eq!(outcome.exit_code(), ExitCode::Installed);
  }

  #[test]
  fn install_dry_run() {
    let fs = MockFs::new();
    let mut config = make_config(make_manifest("0.1.0"));
    config.dry_run = true;
    let outcome = install(&fs, &config).unwrap();
    assert_eq!(
      outcome,
      Outcome::DryRun {
        would_install: true
      }
    );
  }

  #[test]
  fn skip_if_identical() {
    let manifest = make_manifest("0.1.0");
    let json = serde_json::to_string(&manifest).unwrap();
    let fs = MockFs::new().with_file("/project/.agentforge.json", json);
    let config = make_config(manifest);
    let outcome = install(&fs, &config).unwrap();
    assert_eq!(outcome, Outcome::Skipped);
  }

  #[test]
  fn conflict_on_local_edit() {
    let mut existing = make_manifest("0.1.0");
    existing.rules[0].body_checksum = "changed_by_user".into();

    let incoming = make_manifest("0.1.0");
    let json = serde_json::to_string(&existing).unwrap();
    let fs = MockFs::new().with_file("/project/.agentforge.json", json);
    let config = make_config(incoming);
    let outcome = install(&fs, &config).unwrap();

    match outcome {
      Outcome::Conflict { edited_rules } => {
        assert_eq!(edited_rules, vec!["0".to_string()]);
      }
      other => panic!("expected Conflict, got {other:?}"),
    }
  }

  #[test]
  fn force_overwrites_local_edits() {
    let mut existing = make_manifest("0.1.0");
    existing.rules[0].body_checksum = "changed_by_user".into();

    let incoming = make_manifest("0.1.0");
    let json = serde_json::to_string(&existing).unwrap();
    let fs = MockFs::new().with_file("/project/.agentforge.json", json);

    let mut config = make_config(incoming);
    config.force = true;
    let outcome = install(&fs, &config).unwrap();
    assert_eq!(outcome, Outcome::Upgraded);
  }

  #[test]
  fn version_mismatch_returns_error() {
    let existing = make_manifest("0.1.0");
    let incoming = make_manifest("1.0.0");
    let json = serde_json::to_string(&existing).unwrap();
    let fs = MockFs::new().with_file("/project/.agentforge.json", json);
    let config = make_config(incoming);
    let result = install(&fs, &config);
    assert!(result.is_err());
  }

  #[test]
  fn corrupt_existing_manifest_returns_error() {
    let fs = MockFs::new().with_file("/project/.agentforge.json", "not json");
    let config = make_config(make_manifest("0.1.0"));
    let result = install(&fs, &config);
    assert!(result.is_err());
  }
}
